//包名
package test
import com.drools.test.People;

//rule 就是三大块中的规则体，以rule开头，以end 结尾，每个规则文件可以包含多个rule。规则体分为三个部分，LHS RHS 属性 三大部分
//LHS：条件部分又被称之为 LeftHand Side，简称为 LHS，在一个规则当中 when 与 then 中间的部分就是 LHS 部分。
//在 LHS 当中，可以包含 0~n 个条件，如果 LHS 部分没空的话，那么引擎会自动添加一个eval(true)的条件，由于该条件总是返回 true，所以 LHS 为空的规则总是返回 true。
//RHS：结果部分又被称之为 RightHand Side，简称为 RHS，在一个规则当中 then后面部分就是 RHS，只有在 LHS 的所有条件都满足时 RHS 部分才会执行。

rule "rule1"
    salience 1
        when
            $people:People(age>30)//这里就是LHS
        then
            System.out.println("age>30岁的人:"+$people.getName());//RHS
end


rule "rule2"
    salience 2
    when
         $people:People(gender=="男",age>25)
    then
        System.out.println("性别为男,age>25岁的人:"+$people.getName());
     end


rule "rule3"
     salience 3
     when
        $people:People(getName()=="张三")
        then
         System.out.println("名字为:"+$people.getName());
         end